name: Test

on:
  push:
    branches:
      - "master"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20, 22, 24 ]
    name: Node ${{ matrix.node }} tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Run tests
        run: pnpm test
